In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    object 
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.5+ KB


In [5]:
df.drop(['Name','Ticket','PassengerId','Cabin'],axis=1,inplace=True)

In [6]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()
df['Sex']=lc.fit_transform(df['Sex'])
df['Embarked']=lc.fit_transform(df['Embarked'])

In [7]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [11]:
def SVM(x,y):
    X=x
    y=y
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=0)
    from sklearn.svm import SVC
    svm=SVC(gamma=.1,C=100)
    svm.fit(X_train,y_train)
    predecition=svm.predict(X_test)
    from sklearn.metrics import confusion_matrix,accuracy_score
    print(accuracy_score(y_test,predecition))
    print(confusion_matrix(y_test,predecition),'\n')

In [12]:
colum=['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch',
       'Embarked']

for i in colum:
    y=df[i]
    x=df.drop(i,axis=1)
    SVM(x,y)

0.6704119850187266
[[126  31]
 [ 57  53]] 

0.8838951310861424
[[ 63   5   2]
 [  6  35   8]
 [  5   5 138]] 

0.6554307116104869
[[ 48  50]
 [ 42 127]] 

0.7602996254681648
[[159  19   2   0   2   0   0]
 [ 28  35   1   1   0   0   0]
 [  6   0   2   0   0   0   0]
 [  1   3   0   3   0   0   0]
 [  1   0   0   0   1   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]] 

0.7490636704119851
[[184   9   5   0   0   0]
 [ 29   8   2   0   0   1]
 [ 13   6   8   0   0   0]
 [  1   0   0   0   0   0]
 [  1   0   0   0   0   0]
 [  0   0   0   0   0   0]] 

0.7827715355805244
[[ 27   1  21]
 [  0   9  13]
 [ 16   7 173]] 

