In [1]:
import numpy as np
import pandas as pd
 


In [34]:
df=pd.read_csv('train.csv')

In [35]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    object 
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.5+ KB


In [37]:
df.drop(['Name','Ticket','PassengerId'],axis=1,inplace=True)

In [38]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [55]:
from sklearn.preprocessing import LabelEncoder
lc=LabelEncoder()
df['Sex']=lc.fit_transform(df['Sex'])
df['Embarked']=lc.fit_transform(df['Embarked'])

In [56]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [41]:
df.drop('Cabin',axis=1,inplace=True)

In [57]:
df.isnull().sum()
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [80]:
def NB(x,y):
    X=x
    y=y
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=0)
    from sklearn.naive_bayes import GaussianNB
    nb=GaussianNB()
    nb.fit(X_train,y_train)
    predecition=nb.predict(X_test)
    from sklearn.metrics import confusion_matrix,accuracy_score
    print(accuracy_score(y_test,predecition))
    print(confusion_matrix(y_test,predecition),'\n')
    
    

In [81]:
colum=['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch',
       'Embarked']

for i in colum:
    y=df[i]
    x=df.drop(i,axis=1)
    NB(x,y)


0.7528089887640449
[[121  36]
 [ 30  80]] 

0.6966292134831461
[[ 52  13   5]
 [  5  25  19]
 [  5  34 109]] 

0.7153558052434457
[[ 52  46]
 [ 30 139]] 

0.5543071161048689
[[130   8   2  40   2   0   0]
 [ 29   9   0  25   2   0   0]
 [  6   0   1   0   1   0   0]
 [  1   0   0   3   3   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]] 

0.5805243445692884
[[143   9   2  31  13]
 [ 17   5   2  12   4]
 [  7   5   7   6   2]
 [  0   0   0   0   1]
 [  0   0   0   1   0]] 

0.6928838951310862
[[ 23   3  23]
 [  0  10  12]
 [ 23  21 152]] 

