In [3]:
!pip install pyod

     |████████████████████████████████| 102kB 2.6MB/s 
     |████████████████████████████████| 2.1MB 8.2MB/s 
  Created wheel for pyod: filename=pyod-0.8.1-cp36-none-any.whl size=105653 sha256=bb421059a7ca1ba4f43967ab1150931c045e8937d2bcaac32c52e577f11deb17
  Stored in directory: /root/.cache/pip/wheels/2e/ca/18/727e9d98a41f5f4385a97d5b429f3a9c8fbee13f9780c18642
  Created wheel for combo: filename=combo-0.1.1-cp36-none-any.whl size=42111 sha256=8bce8f6e80eb8b934989652fed96c3e6468cd062cdabd4369852122ebbb6d2f4
  Stored in directory: /root/.cache/pip/wheels/55/ec/e5/a2331372c676c467e70c6646e646edf6997d5c4905b8c0f5e6
  Created wheel for suod: filename=suod-0.0.4-cp36-none-any.whl size=2167157 sha256=6e44666eb59dc89d4d3d91e9589642d254116926c2ca1a31148f36c028eb84e7
  Stored in directory: /root/.cache/pip/wheels/57/55/e5/a4fca65bba231f6d0115059b589148774b41faea25b3f2aa27
Successfully built pyod combo suod


In [4]:
import os
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from scipy.io import loadmat

In [5]:
from pyod.models.pca import PCA
from pyod.models.mcd import MCD
from pyod.models.ocsvm import OCSVM
from pyod.models.lof import LOF
from pyod.models.cblof import CBLOF
from pyod.models.knn import KNN
from pyod.models.hbos import HBOS
from pyod.models.abod import ABOD
from pyod.models.iforest import IForest
from pyod.models.feature_bagging import FeatureBagging

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)


In [6]:
from pyod.utils.utility import standardizer
from pyod.utils.utility import precision_n_scores
from sklearn.metrics import roc_auc_score

In [7]:

mat_file_list = ['arrhythmia.mat',
                 'cardio.mat',
                 'glass.mat',
                 'ionosphere.mat',
                 'letter.mat',
                 'lympho.mat',
                 'mnist.mat',
                 'musk.mat',
                 'optdigits.mat',
                 'pendigits.mat',
                 'pima.mat',
                 'satellite.mat',
                 'satimage-2.mat',
                 'shuttle.mat',
                 'vertebral.mat',
                 'vowels.mat',
                 'wbc.mat']

df_columns = ['Data', '#Samples', '# Dimensions', 'Outlier Perc',
              'ABOD', 'CBLOF', 'FB', 'HBOS', 'IForest', 'KNN', 'LOF', 'MCD',
              'OCSVM', 'PCA']
roc_df = pd.DataFrame(columns=df_columns)
prn_df = pd.DataFrame(columns=df_columns)
time_df = pd.DataFrame(columns=df_columns)



In [20]:
random_state = np.random.RandomState(42)
print(random_state)
from time import time
for mat_file in mat_file_list:
    print("\n... Processing", mat_file, '...')
    mat = loadmat(os.path.join('/content/drive/My Drive/Colab Notebooks/lets upgrade AIML/project 1-Anamaly detecion', mat_file))
    X = mat['X']
    y = mat['y'].ravel()
    outliers_fraction = np.count_nonzero(y) / len(y)
    outliers_percentage = round(outliers_fraction * 100, ndigits=4)
    roc_list = [mat_file[:-4], X.shape[0], X.shape[1], outliers_percentage]
    prn_list = [mat_file[:-4], X.shape[0], X.shape[1], outliers_percentage]
    time_list = [mat_file[:-4], X.shape[0], X.shape[1], outliers_percentage]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                        random_state=random_state)
    X_train_norm, X_test_norm = standardizer(X_train, X_test)
    classifiers = {'Angle-based Outlier Detector (ABOD)': ABOD(
        contamination=outliers_fraction),
        'Cluster-based Local Outlier Factor': CBLOF(
            contamination=outliers_fraction, check_estimator=False,
            random_state=random_state),
        'Feature Bagging': FeatureBagging(contamination=outliers_fraction,
                                          random_state=random_state),
        'Histogram-base Outlier Detection (HBOS)': HBOS(
            contamination=outliers_fraction),
        'Isolation Forest': IForest(contamination=outliers_fraction,
                                    random_state=random_state),
        'K Nearest Neighbors (KNN)': KNN(contamination=outliers_fraction),
        'Local Outlier Factor (LOF)': LOF(
            contamination=outliers_fraction),
        'Minimum Covariance Determinant (MCD)': MCD(
            contamination=outliers_fraction, random_state=random_state),
        'One-class SVM (OCSVM)': OCSVM(contamination=outliers_fraction),
        'Principal Component Analysis (PCA)': PCA(
            contamination=outliers_fraction, random_state=random_state),
    }

    for clf_name, clf in classifiers.items():
        t0 = time()
        clf.fit(X_train_norm)
        test_scores = clf.decision_function(X_test_norm)
        t1 = time()
        duration = round(t1 - t0, ndigits=4)
        time_list.append(duration)

        roc = round(roc_auc_score(y_test, test_scores), ndigits=4)
        prn = round(precision_n_scores(y_test, test_scores), ndigits=4)

        print('{clf_name} ROC:{roc}, precision @ rank n:{prn}, '
              'execution time: {duration}s'.format(
            clf_name=clf_name, roc=roc, prn=prn, duration=duration))

        roc_list.append(roc)
        prn_list.append(prn)

    temp_df = pd.DataFrame(time_list).transpose()
    temp_df.columns = df_columns
    time_df = pd.concat([time_df, temp_df], axis=0)

    temp_df = pd.DataFrame(roc_list).transpose()
    temp_df.columns = df_columns
    roc_df = pd.concat([roc_df, temp_df], axis=0)

    temp_df = pd.DataFrame(prn_list).transpose()
    temp_df.columns = df_columns
    prn_df = pd.concat([prn_df, temp_df], axis=0)


RandomState(MT19937)

... Processing arrhythmia.mat ...
Angle-based Outlier Detector (ABOD) ROC:0.7687, precision @ rank n:0.3571, execution time: 1.1755s
Cluster-based Local Outlier Factor ROC:0.7684, precision @ rank n:0.4643, execution time: 1.4187s
Feature Bagging ROC:0.7799, precision @ rank n:0.5, execution time: 0.6295s
Histogram-base Outlier Detection (HBOS) ROC:0.8511, precision @ rank n:0.5714, execution time: 1.355s
Isolation Forest ROC:0.8527, precision @ rank n:0.5714, execution time: 0.4051s
K Nearest Neighbors (KNN) ROC:0.782, precision @ rank n:0.5, execution time: 0.0899s
Local Outlier Factor (LOF) ROC:0.7787, precision @ rank n:0.4643, execution time: 0.0746s


/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:644: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "


Minimum Covariance Determinant (MCD) ROC:0.8228, precision @ rank n:0.4286, execution time: 1.1891s
One-class SVM (OCSVM) ROC:0.7986, precision @ rank n:0.5, execution time: 0.0549s
Principal Component Analysis (PCA) ROC:0.8, precision @ rank n:0.5, execution time: 0.0611s

... Processing cardio.mat ...
Angle-based Outlier Detector (ABOD) ROC:0.5763, precision @ rank n:0.1875, execution time: 0.3595s
Cluster-based Local Outlier Factor ROC:0.8221, precision @ rank n:0.4844, execution time: 0.2124s
Feature Bagging ROC:0.4879, precision @ rank n:0.1406, execution time: 0.7659s
Histogram-base Outlier Detection (HBOS) ROC:0.8453, precision @ rank n:0.4688, execution time: 0.0072s
Isolation Forest ROC:0.9414, precision @ rank n:0.5, execution time: 0.3694s
K Nearest Neighbors (KNN) ROC:0.6959, precision @ rank n:0.2812, execution time: 0.1332s
Local Outlier Factor (LOF) ROC:0.4715, precision @ rank n:0.125, execution time: 0.0935s


/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:644: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "


Minimum Covariance Determinant (MCD) ROC:0.8778, precision @ rank n:0.3906, execution time: 0.71s
One-class SVM (OCSVM) ROC:0.9507, precision @ rank n:0.5938, execution time: 0.1285s
Principal Component Analysis (PCA) ROC:0.9638, precision @ rank n:0.6875, execution time: 0.0052s

... Processing glass.mat ...
Angle-based Outlier Detector (ABOD) ROC:0.7104, precision @ rank n:0.25, execution time: 0.0525s
Cluster-based Local Outlier Factor ROC:0.8506, precision @ rank n:0.25, execution time: 0.0543s
Feature Bagging ROC:0.7043, precision @ rank n:0.25, execution time: 0.0337s
Histogram-base Outlier Detection (HBOS) ROC:0.6524, precision @ rank n:0.0, execution time: 0.0045s
Isolation Forest ROC:0.7195, precision @ rank n:0.25, execution time: 0.2716s
K Nearest Neighbors (KNN) ROC:0.7805, precision @ rank n:0.25, execution time: 0.0074s
Local Outlier Factor (LOF) ROC:0.7774, precision @ rank n:0.25, execution time: 0.0033s
Minimum Covariance Determinant (MCD) ROC:0.7165, precision @ rank 

/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:170: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-380.733523356668684 > -520.529171150752177). You may want to try with a higher value of support_fraction (current value: 0.614).
  RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:170: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-197.224339606050478 > -526.499524761035786). You may want to try with a higher value of support_fraction (current value: 0.614).
  RuntimeWarning)


Angle-based Outlier Detector (ABOD) ROC:0.7813, precision @ rank n:0.3562, execution time: 7.4389s
Cluster-based Local Outlier Factor ROC:0.8447, precision @ rank n:0.4007, execution time: 1.0728s
Feature Bagging ROC:0.7259, precision @ rank n:0.3664, execution time: 54.3788s
Histogram-base Outlier Detection (HBOS) ROC:0.5675, precision @ rank n:0.1199, execution time: 0.0482s
Isolation Forest ROC:0.7801, precision @ rank n:0.2979, execution time: 1.269s
K Nearest Neighbors (KNN) ROC:0.8409, precision @ rank n:0.4144, execution time: 6.9406s
Local Outlier Factor (LOF) ROC:0.7085, precision @ rank n:0.339, execution time: 6.7045s


/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:644: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "


Minimum Covariance Determinant (MCD) ROC:0.863, precision @ rank n:0.3973, execution time: 3.5834s
One-class SVM (OCSVM) ROC:0.8417, precision @ rank n:0.3801, execution time: 5.5355s
Principal Component Analysis (PCA) ROC:0.8396, precision @ rank n:0.3767, execution time: 0.1225s

... Processing musk.mat ...
Angle-based Outlier Detector (ABOD) ROC:0.0809, precision @ rank n:0.0333, execution time: 2.1829s
Cluster-based Local Outlier Factor ROC:1.0, precision @ rank n:1.0, execution time: 0.3695s
Feature Bagging ROC:0.5228, precision @ rank n:0.1667, execution time: 13.825s
Histogram-base Outlier Detection (HBOS) ROC:0.9999, precision @ rank n:0.9667, execution time: 0.0577s
Isolation Forest ROC:0.9996, precision @ rank n:0.9333, execution time: 0.8688s
K Nearest Neighbors (KNN) ROC:0.7348, precision @ rank n:0.2333, execution time: 1.8382s
Local Outlier Factor (LOF) ROC:0.5323, precision @ rank n:0.1333, execution time: 1.7119s
Minimum Covariance Determinant (MCD) ROC:1.0, precision @

/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:644: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "


Minimum Covariance Determinant (MCD) ROC:0.3486, precision @ rank n:0.0, execution time: 1.743s
One-class SVM (OCSVM) ROC:0.4972, precision @ rank n:0.0, execution time: 1.7849s
Principal Component Analysis (PCA) ROC:0.504, precision @ rank n:0.0, execution time: 0.0443s

... Processing pendigits.mat ...
Angle-based Outlier Detector (ABOD) ROC:0.7008, precision @ rank n:0.0308, execution time: 1.2802s
Cluster-based Local Outlier Factor ROC:0.9609, precision @ rank n:0.3077, execution time: 0.3782s
Feature Bagging ROC:0.4687, precision @ rank n:0.0462, execution time: 3.6505s
Histogram-base Outlier Detection (HBOS) ROC:0.9294, precision @ rank n:0.2615, execution time: 0.0137s
Isolation Forest ROC:0.9422, precision @ rank n:0.2769, execution time: 0.6696s
K Nearest Neighbors (KNN) ROC:0.7602, precision @ rank n:0.0462, execution time: 0.4912s
Local Outlier Factor (LOF) ROC:0.481, precision @ rank n:0.0462, execution time: 0.4419s
Minimum Covariance Determinant (MCD) ROC:0.8271, precisio

/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:170: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-49.541490230701058 > -75.681926842947846). You may want to try with a higher value of support_fraction (current value: 0.503).
  RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:170: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-50.022992269211016 > -76.128980282328556). You may want to try with a higher value of support_fraction (current value: 0.503).
  RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/covariance/_robust_covariance.py:170: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-48.588090860494653 > -73.914905941043045). You may want to try with a higher value of support_fraction (current value: 0.503).
  RuntimeWarning)
/usr/local/lib/p

Minimum Covariance Determinant (MCD) ROC:0.9903, precision @ rank n:0.7534, execution time: 19.223s
One-class SVM (OCSVM) ROC:0.9922, precision @ rank n:0.9553, execution time: 62.9821s
Principal Component Analysis (PCA) ROC:0.9902, precision @ rank n:0.9503, execution time: 0.0344s

... Processing vertebral.mat ...
Angle-based Outlier Detector (ABOD) ROC:0.2797, precision @ rank n:0.0, execution time: 0.0574s
Cluster-based Local Outlier Factor ROC:0.3908, precision @ rank n:0.0, execution time: 0.0459s
Feature Bagging ROC:0.3027, precision @ rank n:0.0, execution time: 0.0379s
Histogram-base Outlier Detection (HBOS) ROC:0.2695, precision @ rank n:0.0, execution time: 0.0025s
Isolation Forest ROC:0.3576, precision @ rank n:0.0, execution time: 0.2744s
K Nearest Neighbors (KNN) ROC:0.318, precision @ rank n:0.0, execution time: 0.0082s
Local Outlier Factor (LOF) ROC:0.318, precision @ rank n:0.0, execution time: 0.0032s
Minimum Covariance Determinant (MCD) ROC:0.3308, precision @ rank n

In [14]:
X = mat['X']
y = mat['y'].ravel()
print(X)
print(y)
print(mat_file)
roc_list = [mat_file[:-4], X.shape[0], X.shape[1], outliers_percentage]
print(roc_list)

[[0.31042643 0.15725397 0.30177597 ... 0.44261168 0.27833629 0.11511216]
 [0.2886554  0.20290835 0.28912998 ... 0.25027491 0.31914055 0.17571822]
 [0.11940934 0.0923233  0.11436666 ... 0.21398625 0.17445299 0.14882592]
 ...
 [0.72360263 0.33682787 0.7532997  ... 1.         0.49083383 0.28105733]
 [0.52103744 0.0226581  0.54598853 ... 0.91202749 0.59846245 0.41886396]
 [0.32367836 0.49983091 0.33542948 ... 0.52268041 0.41119653 0.41492851]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [21]:
print('Time complexity')
time_df



Time complexity


Data #Samples # Dimensions  ...      MCD    OCSVM     PCA
0  arrhythmia      452          274  ...   1.1891   0.0549  0.0611
0      cardio     1831           21  ...     0.71   0.1285  0.0052
0       glass      214            9  ...     0.05   0.0031  0.0035
0  ionosphere      351           33  ...   0.0924   0.0081  0.0038
0      letter     1600           32  ...   1.4813   0.1249  0.0068
0      lympho      148           18  ...   0.0496   0.0024  0.0025
0       mnist     7603          100  ...   3.5834   5.5355  0.1225
0        musk     3062          166  ...  15.8699   1.4157  0.1169
0   optdigits     5216           64  ...    1.743   1.7849  0.0443
0   pendigits     6870           16  ...   2.8275   1.2312  0.0099
0        pima      768            8  ...   0.0685    0.019  0.0022
0   satellite     6435           36  ...   2.9225   1.7311   0.022
0  satimage-2     5803           36  ...   2.8898   1.4226  0.0204
0     shuttle    49097            9  ...   19.223  62.9821  0.0344
0   vertebral      240            6  ...   0.0595   0.0033  0.0021
0      vowels     1456           12  ...   0.9607   0.0716  0.0034
0         wbc      378           30  ...   0.0895   0.0089  0.0036

[17 rows x 14 columns]

In [22]:
print('ROC Performance')
roc_df

ROC Performance


Data #Samples # Dimensions  ...     MCD   OCSVM     PCA
0  arrhythmia      452          274  ...  0.8228  0.7986     0.8
0      cardio     1831           21  ...  0.8778  0.9507  0.9638
0       glass      214            9  ...  0.7165  0.6189   0.622
0  ionosphere      351           33  ...  0.9399  0.8372  0.7971
0      letter     1600           32  ...  0.7499  0.5744    0.48
0      lympho      148           18  ...  0.9127  0.9636  0.9818
0       mnist     7603          100  ...   0.863  0.8417  0.8396
0        musk     3062          166  ...       1       1       1
0   optdigits     5216           64  ...  0.3486  0.4972   0.504
0   pendigits     6870           16  ...  0.8271    0.93  0.9332
0        pima      768            8  ...  0.7047  0.6423  0.6639
0   satellite     6435           36  ...   0.792   0.636  0.5783
0  satimage-2     5803           36  ...  0.9946  0.9976  0.9841
0     shuttle    49097            9  ...  0.9903  0.9922  0.9902
0   vertebral      240            6  ...  0.3308  0.4087  0.3397
0      vowels     1456           12  ...  0.6779  0.7415  0.5787
0         wbc      378           30  ...  0.8986  0.9408  0.9324

[17 rows x 14 columns]

In [23]:
print('Precision @ n Performance')
prn_df

Precision @ n Performance


Data #Samples # Dimensions  ...     MCD   OCSVM     PCA
0  arrhythmia      452          274  ...  0.4286     0.5     0.5
0      cardio     1831           21  ...  0.3906  0.5938  0.6875
0       glass      214            9  ...       0    0.25    0.25
0  ionosphere      351           33  ...  0.8571  0.7143  0.5893
0      letter     1600           32  ...   0.075     0.1    0.05
0      lympho      148           18  ...     0.6     0.6     0.8
0       mnist     7603          100  ...  0.3973  0.3801  0.3767
0        musk     3062          166  ...  0.9667       1       1
0   optdigits     5216           64  ...       0       0       0
0   pendigits     6870           16  ...  0.0615  0.2923  0.3385
0        pima      768            8  ...  0.4787  0.4574     0.5
0   satellite     6435           36  ...  0.6747  0.5224  0.4559
0  satimage-2     5803           36  ...  0.5185  0.9259  0.8519
0     shuttle    49097            9  ...  0.7534  0.9553  0.9503
0   vertebral      240            6  ...       0       0       0
0      vowels     1456           12  ...       0  0.2941  0.1176
0         wbc      378           30  ...     0.4     0.5     0.6

[17 rows x 14 columns]